name: Deploy to Azure VM
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy changes to Node 1
        uses: appleboy/ssh-action@master
        with:
          host: 52.237.80.158
          username: azureuser
          key: ${{ secrets.DEPLOYMENT_NODE_1_SSH_PRIVATE_KEY }}
          timeout-minutes: 5
          continue-on-error: true
          script: |
            cd ~/Transaction-Management
            git pull
            npm install
            echo -n "export NODE_NUM_CONFIGURATION=1" >> .env
            pm2 stop my-app                # Stop the existing PM2 process (if any)
            pm2 delete my-app              # Delete the existing PM2 process (if any)
            pm2 start index.js --name my-app  # Start your Node.js application with PM2
      - name: Deploy changes to Node 2
        uses: appleboy/ssh-action@master
        with:
          host: 52.237.80.166
          username: azureuser # replace with the appropriate username
          key: ${{ secrets.DEPLOYMENT_NODE_2_SSH_PRIVATE_KEY }} # replace with the appropriate SSH private key secret
          timeout-minutes: 5
          continue-on-error: true
          script: |
            cd ~/Transaction-Management
            git pull
            npm install
            echo -n "export NODE_NUM_CONFIGURATION=2" >> .env
            pm2 stop my-app                # Stop the existing PM2 process (if any)
            pm2 delete my-app              # Delete the existing PM2 process (if any)
            pm2 start index.js --name my-app  # Start your Node.js application with PM2
      - name: Deploy changes to Node 3
        uses: appleboy/ssh-action@master
        with:
          host: 104.43.93.188
          username: azureuser # replace with the appropriate username
          key: ${{ secrets.DEPLOYMENT_NODE_3_SSH_PRIVATE_KEY }} # replace with the appropriate SSH private key secret
          timeout-minutes: 5
          continue-on-error: true
          script: |
            cd ~/Transaction-Management
            git pull
            npm install
            echo -n "export NODE_NUM_CONFIGURATION=3" >> .env
            pm2 stop my-app                # Stop the existing PM2 process (if any)
            pm2 delete my-app              # Delete the existing PM2 process (if any)
            pm2 start index.js --name my-app  # Start your Node.js application with PM2